{ pkgs, modulesPath, inputs, outputs, ... }:
{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [
    podman
    podman-compose
  ];

  services.openssh.enable = true;

  virtualisation.containers.enable = true;

  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };

  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      omni-tools = {
        image = "iib0011/omni-tools:latest";
        autoStart = true;
        ports = [
          "8080:80"
        ];
        extraOptions = [
          "--pull=always"
        ];
        volumes = [
          "/var/lib/omni-tools:/app/data:rw"
        ];
      };
    };
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/omni-tools 0755 root root - -"
  ];

  networking.firewall.allowedTCPPorts = [ 8080 ];

  system.stateVersion = "25.05";
}