{ pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];
	
  environment.systemPackages = with pkgs; [
		ansible
    ansible-lint
    terraform
    sshpass
    lazygit

    # This is required for the ansibleguy.opnsense ansible role
    (python3.withPackages (ps: with ps; [
      httpx
    ]))
  ];


  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  system.stateVersion = "24.05";
}
