{ pkgs, modulesPath, inputs, outputs, ... }:

{
  imports = [
    # Autogenerated configuration specific to the iso, and not included in repo
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];
	
  environment.systemPackages = with pkgs; [
    git
    gitAndTools.git-lfs
  ];

  services.forgejo.enable = true;

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Firewall configuration
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 80 443 ];  # SSH, HTTP, HTTPS
  };

  system.stateVersion = "25.05";
}
